### PR TITLE
mention similar projects

### PR DESCRIPTION
**Pull request by KiaraGrouwstra**

### CODE REVIEW

**Review by dijs — APPROVED** [review]

**Comment by dijs** [comment]
Thank you!

**Comment by KiaraGrouwstra** [comment]
I just tried converting the project to TypeScript as well ([branch](https://github.com/tycho01/parsz/tree/add-types)), just to make sure I know what's what before touching anything else. Maybe the changes look a bit big for a PR -- `tslint` made me change some small silly stuff (punctuation, import/key order, etc.). Anyway, figured I'd tell. :)

**Comment by dijs** [comment]
Surprised eslint is not catching those errors. I may need to spend some time doing some clean up on this project. It is not priority for me right now.

**Comment by KiaraGrouwstra** [comment]
yeah, np. trying to adapt a bit to my use-case too. already scraped beforehand, so just wanna extract in batch. I now generalized the transformations so users could bring their own.

**Pull request merged**
